version: "3"
services:
    main:
        build: .
        image: jestrr/nomad:0.0.1
        entrypoint: ["pm2", "start", "/home/app/src/config/pm2.config.js", "--no-daemon"]
        volumes:
            - ./src:/home/app/src
            - ./server:/home/app/server
            - ./pub:/home/app/pub
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                max_attempts: 3
                condition: on-failure
        ports:
            # HOST:CONTAINER
            - "7010:4000"
        labels:
            com.consul.service: nomad
        environment:
            PUB_FILES: ./pub/
            BIN: ./server/bin/
            OUTPUT_FILES: ./server/output/

            # Consul
            SERVICE_NAME: nomad
            SERVICE_PORT: 7010
            REGISTER_SERVICE: "false"
            IMAGE_VER: 0.0.1
