version: "3.5"
services:
    main:
        build:
            context: .
            target: prod
        image: registry.codeopensrc.com/kc/nomad:0.0.1
        ports:
            - "7010:80"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
                max_failure_ratio: .3
                order: start-first
            restart_policy:
                max_attempts: 3
                condition: on-failure
            placement:
                preferences:
                    - spread: node.labels.dc
                    - spread: node.labels.az
